name: Create Empty Commit

on:
  workflow_dispatch:

jobs:
  create-empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_USER_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "Pranjal Gupta"
          git config user.email "pranjalakg@gmail.com"

      - name: Create and push empty commit
        run: |
          git commit --allow-empty -m "Empty commit"
          git push
