name: Trigger Deploy

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to monitor

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit message and create empty commit
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_USER_TOKEN }}
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $COMMIT_MESSAGE == trigger-deploy:* ]]; then
            git config user.name "Pranjal Gupta"
            git config user.email "pranjalakg@gmail.com"
            git commit --allow-empty -m "Empty commit to trigger deploy"
            git push
          else
            echo "Commit message does not start with 'trigger-deploy:'. Skipping empty commit."
          fi
