name: Conditional Deploy

on:
  push:
    branches:
      - '*'

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_USER_TOKEN }}

      - name: Get commit message
        id: get_commit_message
        run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Set branch name
        id: set_branch
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"

      - name: Check commit message and deploy
        if: startsWith(steps.get_commit_message.outputs.commit_message, 'trigger-deploy')
        run: |
          echo "Commit message starts with 'trigger-deploy'. Proceeding with deployment."
          echo "Current branch: ${{ steps.set_branch.outputs.branch_name }}"
          
          # Configure Git
          git config user.name "Pranjal Gupta"
          git config user.email "pranjalakg@gmail.com"
          
          # Create and push empty commit
          git commit --allow-empty -m "Deployment triggered from ${{ steps.set_branch.outputs.branch_name }}"
          git push origin ${{ steps.set_branch.outputs.branch_name }}
