name: Test

on: 
  push:
    branches: [staging, trying]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sample
        run: echo "Hi"
