name: Conditional Deploy

on:
  push:
    branches:
      - '*'

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        id: check_commit
        run: |
          commit_message=$(git log -1 --pretty=format:%s ${{ github.sha }})
          if [[ $commit_message == trigger-deploy* ]]; then
            echo "::set-output name=should_deploy::true"
          else
            echo "::set-output name=should_deploy::false"
          fi

      - name: Checkout repository
        if: steps.check_commit.outputs.should_deploy == 'true'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_USER_TOKEN }}

      - name: Set branch name
        if: steps.check_commit.outputs.should_deploy == 'true'
        id: set_branch
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"

      - name: Deploy
        if: steps.check_commit.outputs.should_deploy == 'true'
        run: |
          echo "Commit message starts with 'trigger-deploy'. Proceeding with deployment."
          echo "Current branch: ${{ steps.set_branch.outputs.branch_name }}"
          
          # Configure Git
          git config user.name "Pranjal Gupta"
          git config user.email "pranjalakg@gmail.com"
          
          # Create and push empty commit
          git commit --allow-empty -m "Deployment triggered from ${{ steps.set_branch.outputs.branch_name }}"
          git push origin ${{ steps.set_branch.outputs.branch_name }}
